# Build stage
FROM cgr.dev/chainguard/python:latest-dev AS builder

WORKDIR /app

COPY app/ /app

RUN python -m venv venv
ENV PATH="/app/venv/bin":$PATH

RUN pip install Flask

# Final stage
FROM cgr.dev/chainguard/python:latest

WORKDIR /app

COPY --from=builder /app/venv /app/venv
ENV PATH="/app/venv/bin:$PATH" 

COPY app/ /app

EXPOSE 5000

ENTRYPOINT ["python", "app.py"]
